### ISSUE TITLE
Touring handicap discourages mods

### ISSUE THREAD

**Issue by barm** [86challenge/rules#34]
At Sonoma, drivers in stock or street class could have finished P1 or P2 in touring and believe that this discourages modifications. Discuss!

**Comment by sauprankul** [comment]
https://github.com/86challenge/rules/pull/36

**Comment by sauprankul** [comment]
Some possibly competitive 7 point builds:

## Gen 1
### HPDE Classic
- V730 (2)-
- engine bolt-ons (0.5)-
- LSD (0.5)
- E85 (1.5)
- small wing (1)
- adjustable coilovers (1)
- hood vents (0.5)
### CARB Legal
- 18" SX2 (1)
- lightweight drivetrain (0.5)
- LSD (0.5)
-  adjustable coilovers (1)
- medium wing (1.5)
- 125mm splitter (1.5)
- hood vents (0.5)
- underbody aero (0.5)
### Straight Line Demon
- SX2 (-1)
- engine bolt-ons (0.5)
-  forced induction (4.5)
- E85 (2.5)
- underbody/diffuser aero (0.5)

## Gen 2
### Street Premium
- Gen 2 (2)
-  coilovers + remotes (1.5)
-  V730 (2)
- hood vents (0.5)
-  underbody aero (0.5)
- LSD (0.5)
### Breathe Free
- Gen 2 (2)
- 18" SX2 (1)
- engine bolt-ons (0.5)
- lightweight drivetrain (0.5)
- E85 (1.5), hood vents (0.5)
- coilovers (0.5)
- underbody aero (0.5)
### GREIP
- Gen 2 (2)
- small wing (1)
- adjustable coilovers (1)
- RE71RS (3)
### Big Wang Gang
- Gen 2 (2)
- SX2 (-1)
- adjustable coilovers (1)
-  tune (0.5)
- 125mm splitter (1.5)
-  big wing (2)
- hood vents (0.5)
- underbody aero (0.5)

IMO, any more than this, and it becomes hard to reasonably use the points for gen 1.

**Comment by itsmang0** [comment]
If handy cap gets adjusted. First 3 points should be waived. Since Street Class builds (3 points) have no time adjustments.

**Comment by wlorne** [comment]
Problem: 
The current touring handicap table does not take into account diminishing return on large aero modifications. As a result, high point value aero-builds are heavily penalized.

Solution:
I propose two changes. First - BOP should be dropped. Touring should have minimum 3.5pt build, and maximum of 7pts. This allows for diverse, 200tw based builds that can utilize either Super/Enduro 200s, small aero (canards/underbody/small lips), additional power (header/tune), or other strange concoctions. 3pt and under builds should run Street as long as they meet the requirements, otherwise they may run touring but will likely be uncompetitive. That is ok - people should decide on a class and build to it. A 7pt limit would also allow cars to crossover with SpeedSF S4 rules, which allow for similar modifications before hitting 13.5PT S4 limit.

Second change: Make unlimited class 7.5pts and up, no BOP. Currently there are only a few cars which would fit into this class, and they are all modified similarly. Larger aero, header/tune, super 200s. The pace of these cars is far more dependent on developing a cohesive build rather than simply bolting on speed, thus the point system is less relevant (ie - adding more aero won't necessarily make them faster). This class should be for more experimentation and pushing limits of chassis.
